<a href="https://colab.research.google.com/github/kalai2315/kalai2315/blob/NLP-Projects-and-case-studies/Restaurant_Reviews_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as nd
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("/content/Restaurant_Reviews.tsv", sep="\t", quoting=3)

In [4]:
data.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [5]:
data.tail()

Review  Liked
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

In [7]:
data['Liked'].value_counts()

1    500
0    500
Name: Liked, dtype: int64

##Cleaning Text Data

In [9]:
import nltk
import re

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [11]:
from nltk.corpus import stopwords

In [12]:
data['Review'][0]

'Wow... Loved this place.'

In [16]:
review=re.sub('[^a-zA-Z]', ' ', data['Review'][0])


'Wow    Loved this place '

In [18]:
review

'Wow    Loved this place '

In [20]:
review =review.lower()

In [21]:
review


'wow    loved this place '

In [23]:
review =review.split()


In [24]:
review


['wow', 'loved', 'this', 'place']

In [ ]:
stopwords.words('english')

In [26]:
p_review=[]
for word in review:
  if word not in stopwords.words('english'):
    p_review.append(word)

In [27]:
p_review

['wow', 'loved', 'place']

In [29]:
review=[word for word in review if word not in stopwords.words('english')]

In [30]:
review

['wow', 'loved', 'place']

In [31]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [32]:
review=[ps.stem(word)for word in review]

In [33]:
review

['wow', 'love', 'place']

In [35]:
review=" ".join(review)

In [37]:
print(review)

wow love place


In [39]:
corpus=[]
ps=PorterStemmer()
for i in range(len(data)):


  review=re.sub('[^a-zA-Z]', ' ', data['Review'][i])
  review =review.lower()
  review =review.split()
  review=[ps.stem(word)for word in review if word not in stopwords.words('english')]
  review=" ".join(review)
  corpus.append(review)



###Bag Of Words Model


```
# This is formatted as code
```



In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [44]:
cv=CountVectorizer(max_features=1500)

In [47]:
x=cv.fit_transform(corpus).toarray()

In [48]:
x.shape

(1000, 1500)

In [49]:
y=data.iloc[:, 1].values

In [50]:
y.shape

(1000,)

In [51]:
y[: 10]

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

### Apply Naive Bayes Algorithm


In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(x,y, test_size=0.20, random_state=0)

In [54]:
X_train.shape,X_test.shape

((800, 1500), (200, 1500))

In [55]:
y_train.shape,y_test.shape

((800,), (200,))

In [56]:
from sklearn.naive_bayes import GaussianNB

In [57]:
classifier=GaussianNB()

In [58]:
classifier.fit(X_train,y_train)

GaussianNB()

In [59]:
y_pred=classifier.predict(X_test)

In [60]:
y_pred

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1])

In [65]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [62]:
accuracy_score(y_test,y_pred)

0.73

In [63]:
200*0.73

146.0

In [66]:
confusion_matrix(y_test, y_pred)

array([[55, 42],
       [12, 91]])

In [67]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.57      0.67        97
           1       0.68      0.88      0.77       103

    accuracy                           0.73       200
   macro avg       0.75      0.73      0.72       200
weighted avg       0.75      0.73      0.72       200

