<a href="https://colab.research.google.com/github/kalai2315/kalai2315/blob/NLP-Projects-and-case-studies/Yelp_Amazon_IMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_yelp = pd.read_csv('/content/yelp_labelled.txt', sep='\t',header=None)

In [4]:
df_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [5]:
df_yelp.tail()

0  1
995  I think food should have flavor and texture an...  0
996                           Appetite instantly gone.  0
997  Overall I was not impressed and would not go b...  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

In [6]:
df_yelp.shape

(1000, 2)

In [7]:
df_yelp.isna().sum()

0    0
1    0
dtype: int64

In [8]:
df_yelp.describe()

1
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

In [4]:
column_name=['Review','Sentiments']
df_yelp.columns=column_name

In [10]:
df_yelp.head()

Review  Sentiments
0                           Wow... Loved this place.           1
1                                 Crust is not good.           0
2          Not tasty and the texture was just nasty.           0
3  Stopped by during the late May bank holiday of...           1
4  The selection on the menu was great and so wer...           1

In [5]:
df_yelp.shape

(1000, 2)

In [6]:
df_amazon = pd.read_csv('/content/amazon_cells_labelled.txt', sep='\t',header=None)

In [7]:
df_amazon

0  1
0    So there is no way for me to plug it in here i...  0
1                          Good case, Excellent value.  1
2                               Great for the jawbone.  1
3    Tied to charger for conversations lasting more...  0
4                                    The mic is great.  1
..                                                 ... ..
995  The screen does get smudged easily because it ...  0
996  What a piece of junk.. I lose more calls on th...  0
997                       Item Does Not Match Picture.  0
998  The only thing that disappoint me is the infra...  0
999  You can not answer calls with the unit, never ...  0

[1000 rows x 2 columns]

In [8]:
df_amazon.columns=column_name

In [9]:
df_amazon.head()

Review  Sentiments
0  So there is no way for me to plug it in here i...           0
1                        Good case, Excellent value.           1
2                             Great for the jawbone.           1
3  Tied to charger for conversations lasting more...           0
4                                  The mic is great.           1

In [18]:
df_amazon.shape

(1000, 2)

In [10]:
df_imdb = pd.read_csv('/content/imdb_labelled.txt', sep='\t',header=None)

In [11]:
df_imdb

0  1
0    A very, very, very slow-moving, aimless movie ...  0
1    Not sure who was more lost - the flat characte...  0
2    Attempting artiness with black & white and cle...  0
3         Very little music or anything to speak of.    0
4    The best scene in the movie was when Gerardo i...  1
..                                                 ... ..
743  I just got bored watching Jessice Lange take h...  0
744  Unfortunately, any virtue in this film's produ...  0
745                   In a word, it is embarrassing.    0
746                               Exceptionally bad!    0
747  All in all its an insult to one's intelligence...  0

[748 rows x 2 columns]

In [12]:
df_imdb.columns=column_name

In [13]:
df_imdb.head()

Review  Sentiments
0  A very, very, very slow-moving, aimless movie ...           0
1  Not sure who was more lost - the flat characte...           0
2  Attempting artiness with black & white and cle...           0
3       Very little music or anything to speak of.             0
4  The best scene in the movie was when Gerardo i...           1

In [24]:
df_imdb.shape

(748, 2)

Append all the data in a single dataframe:

In [14]:
df=df_yelp.append([df_amazon,df_imdb],ignore_index=True)

<ipython-input-14-a57b70be3671>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df_yelp.append([df_amazon,df_imdb],ignore_index=True)


In [15]:
df

Review  Sentiments
0                              Wow... Loved this place.           1
1                                    Crust is not good.           0
2             Not tasty and the texture was just nasty.           0
3     Stopped by during the late May bank holiday of...           1
4     The selection on the menu was great and so wer...           1
...                                                 ...         ...
2743  I just got bored watching Jessice Lange take h...           0
2744  Unfortunately, any virtue in this film's produ...           0
2745                   In a word, it is embarrassing.             0
2746                               Exceptionally bad!             0
2747  All in all its an insult to one's intelligence...           0

[2748 rows x 2 columns]

In [16]:
df.shape

(2748, 2)

In [17]:
df['Sentiments'].value_counts()

1    1386
0    1362
Name: Sentiments, dtype: int64

In [18]:
df.isnull().sum()

Review        0
Sentiments    0
dtype: int64

In [19]:
x= df['Review']


In [20]:
y= df['Sentiments']

In [ ]:
#Remove stopwords, punctuations, apply lematisation

In [21]:
import string

In [22]:
punct=string.punctuation

In [40]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [23]:
from spacy.lang.en.stop_words import STOP_WORDS

In [24]:
stopwords=list(STOP_WORDS)

In [ ]:
stopwords

In [25]:
import spacy
nlp=spacy.load('en_core_web_sm')

In [26]:
def text_cleaning(sentence):
  doc=nlp(sentence)
  tokens=[]
  for token in doc:
    if token.lemma_!="_PRON-":
      temp=token.lemma_.lower().strip()
    else:
      temp=token.lower_
    tokens.append(temp)

  cleaned_tokens=[]
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens


In [27]:
text_cleaning("In a word, it is embarrassing.		")

['word', 'embarrassing']

**Vectorisation Feature Engineering(TF-IDF)**


In [28]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [30]:
tfidf=TfidfVectorizer(tokenizer=text_cleaning)
#tokenisation will bw done according to this function

classifier=LinearSVC()

**Train the Model**

```
# This is formatted as code
```



In [32]:
from sklearn.model_selection import train_test_split


In [33]:
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [34]:
x_train.shape,x_test.shape

((2198,), (550,))

In [35]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

Fit the x_train and y_train

In [36]:
clf=Pipeline([('tfidf',tfidf),('clf',classifier)])

In [37]:
clf.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_cleaning at 0x79a3e044fe20>)),
                ('clf', LinearSVC())])

Predict the Test Set Results

In [38]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [39]:
y_pred=clf.predict(x_test)

In [40]:
confusion_matrix(y_test,y_pred)

array([[201,  78],
       [ 50, 221]])

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [42]:
accuracy_score(y_test,y_pred)

0.7672727272727272

In [44]:
clf.predict(["Exceptionally bad!"])

array([0])

In [45]:
clf.predict(["Wow... Loved this place."])

array([1])